version: '3'

services:
  web:
    restart: always
    image: nginx
    ports:
      - '8084:80'
    volumes:
      - ./app/build:/usr/share/nginx/html/web_app
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
  server:
    container_name: server
    build: ./server
    ports:
      - '3200:3200'
    links:
      - mongo
    depends_on:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    expose:
      - '27017'
    ports:
      - '27017:27017'
    volumes:
      - './db:/data/db'
